### ISSUE TITLE
Automatic reconnection

### ISSUE THREAD

**Issue by 11qu1d** [sam-mosleh/signalr-async#4]
Hi, first of all thank you for all your work on this project. It really helps.

My question is around how to handle sudden disconnections and how to force a re-connection without having to restart the main loop?

Thanks!

**Comment by sam-mosleh** [comment]
Hey @11qu1d.  There is a flag in clients for that. if you set reconnect_policy (which is set by default) it will try to reconnect automatically and you don't need to force a reconnection manually.

**Comment by 11qu1d** [comment]
Hi @sam-mosleh, sorry for the delayed reply. Yes, this flag is enabled by default in the library but it looks like after a disconnection and subsequent re-connection the user-defined hub function `operations` is not invoked:

```
02-Dec-21 13:55:17 - INFO - (MainThread) - on_connect - Connected...
02-Dec-21 13:55:17 - INFO - (MainThread) - operations - Processing new batch!
02-Dec-21 13:55:17 - INFO - (MainThread) - operations - {'type': 0, 'state': 1912740}
02-Dec-21 13:55:29 - INFO - (MainThread) - operations - Processing new batch!
02-Dec-21 13:55:53 - WARNING - (MainThread) - _timeout_handler - No message received in a long time
02-Dec-21 13:55:53 - INFO - (MainThread) - on_disconnect - Disconnecting...
02-Dec-21 13:55:54 - ERROR - (MainThread) - _consumer - Client cannot connect
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/async/venv/lib/python3.8/site-packages/signalr_async/client.py", line 146, in _consumer
    messages = await self._connection.receive()
  File "/Users/user/PycharmProjects/async/venv/lib/python3.8/site-packages/signalr_async/connection.py", line 118, in receive
    return self._read_message(await self._receive_raw(timeout=timeout))
  File "/Users/user/PycharmProjects/async/venv/lib/python3.8/site-packages/signalr_async/connection.py", line 100, in _receive_raw
    raise ConnectionClosed() from None
signalr_async.exceptions.ConnectionClosed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/PycharmProjects/async/venv/lib/python3.8/site-packages/signalr_async/client.py", line 157, in _consumer
    await self._start_connection()
  File "/Users/user/PycharmProjects/async/venv/lib/python3.8/site-packages/signalr_async/client.py", line 106, in _start_connection
    if await self._connection.start():
  File "/Users/user/PycharmProjects/async/venv/lib/python3.8/site-packages/signalr_async/connection.py", line 57, in start
    raise ConnectionInitializationError("Client cannot connect") from e
signalr_async.exceptions.ConnectionInitializationError: Client cannot connect
02-Dec-21 13:56:09 - INFO - (MainThread) - on_connect - Connected...
```
After the `on_connect` function is fired, `operations` is never invoked again and there is no activity after that apart from keep-alive.

Thanks

**Comment by sam-mosleh** [comment]
I think the reasonable solution in such a condition is to raise an exception.
I'll fix it ASAP.

**Comment by 11qu1d** [comment]
Thanks for the quick response! I just tried again with version 2.3.1 but no luck. Just to make sure its not some implementation bug on my side here is a small sample of what im trying to do:

```
import asyncio
from signalr_async.netcore import Hub, Client
from signalr_async.netcore.protocols import JsonProtocol


class MyHub(Hub):
    async def on_connect(self, connection_id: str) -> None:
        """Will be awaited after connection established"""
        print("Connected...")

    async def on_disconnect(self) -> None:
        """Will be awaited after client disconnection"""
        print("Disconnecting...")

    async def operations(self) -> None:
        """Invoke (method) on server"""
        return await self.invoke('SubscribeToOperations')


hub = MyHub("v1/events")


@hub.on("operations")
async def operations(operation):
    print(operation)


async def main():
    while True:
        async with Client(
                "http://192.168.20.10:5000",
                hub,
                connection_options={
                    "protocol": JsonProtocol(),
                },
                keepalive_interval=1

        ) as client:
            await hub.operations()
            await client.wait()


asyncio.run(main())
```
All i do to test it is after running it normally i just turn off my wifi for a few seconds and then turn it back on to simulate a disconnect. This results in what i mentioned in the previous post above.

Thanks

**Comment by 11qu1d** [comment]
I now have a super hacky workaround where i use `exit()` in the `on_disconnect` function and let docker restart the app and attempt to reconnect... There should be some other way to do this.

**Comment by sam-mosleh** [comment]
I see. when your connection to the server is lost, you will still be awaiting the client.wait() method and after reconnection, you should invoke **SubscribeToOperations** again in order to be able to get new operations data.
The solution is to invoke **SubscribeToOperations** on every connect which is something like this:
```python
class MyHub(Hub):
    async def on_connect(self, connection_id: str) -> None:
        """Will be awaited after connection established"""
        print("Connected...")
        await self.operations()

    async def on_disconnect(self) -> None:
        """Will be awaited after client disconnection"""
        print("Disconnecting...")

    async def operations(self) -> None:
        """Invoke (method) on server"""
        return await self.invoke('SubscribeToOperations')
```

**Comment by 11qu1d** [comment]
Thanks, that solved it! Closing this issue.
